apiVersion: tenancy.kcp.dev/v1alpha1
kind: ClusterWorkspaceType
metadata:
  name: team
  annotations:
    bootstrap.kcp.dev/battery: cluster-workspace-types
spec:
  extend:
    with:
    - name: universal
      path: root
  defaultChildWorkspaceType:
    name: universal
    path: root
  limitAllowedParents:
    types:
    - name: organization
      path: root
    - name: team
      path: root
